### ISSUE TITLE
No apps listed for .rb and .py files

### ISSUE THREAD

**Issue by kaecy** [SimpleMobileTools/Simple-File-Manager#126]
AndroidManifest.xml:
``` xml
...

  <data mimeType="text/*" />

...
```
This only matches .cpp and .cs files. Something changed it used to be able to match .rb and .py files as text/plain.

**Comment by tibbi** [comment]
thanks, it should be fixed in the next version. Here is a map of all extensions and their mimetypes, that appears to be the most reliable way of doing it, let me know if something else is missing.
https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/String.kt#L114

**Comment by kaecy** [comment]
Thank you. That helps.

**Comment by kaecy** [comment]
I'm on 2.7 of file manager now and it stopped working for .cpp and .cs files. And .py and .rb files still don't open. I remember it used to show a list of possible apps that can be used to open a file but not anymore.

I have a text editor installed so I should be able to open .json and .csv files with that but I can't because it tells me there are no apps installed for those file.

**Comment by tibbi** [comment]
ok ill take a look at it someday

**Comment by kaecy** [comment]
Okay.

So I've reopened my basic file manager and fiddled with it a bit to use Intent.createChooser and it works!

For any types I don't have a type for I use:
``` java
if (itemType == null)
{
  Intent intent = new Intent(Intent.ACTION_VIEW);
  intent.setDataAndType(selectedItem.toUri(), "*/*");

  Intent openFile = Intent.createChooser(intent, "Open");
  startActivity(openFile);
}
```
Just pass in "\*/\*" for type and it will list all the possible apps for a view action intent. It can also be done without creating a chooser intent.

By the way .apk don't open either. I think this is bigger than just those files I have listed. Hope that helps.

**Comment by tibbi** [comment]
it should be improved in the next version, with */* as a fallback if really nothing gives more exact mimetype

**Comment by kaecy** [comment]
It's working. Can be improved on but it's enough for now.

![](https://puu.sh/ypQSv/29b0117a05.png)

Don't like that you switched to content uri. I liked the file uri. File uri pointed to the physical file and were easier to use. But I'm not asking you to change it. I've made modifications(https://github.com/kaecy/run-ra-code/blob/master/src/org/android/FileMethods.java) to supported both content and file uri in case you ever decided to go back to how it was.

**Comment by tibbi** [comment]
From Android 7+ Google enforces content uri, so for consistency I use it everywhere. I still send the real uri with the "real_file_path" extra so I can identify the path, as the google behaviour just sucks, but not much I can do about it.
